config/routes.rb
Rails.application.routes.draw do

   root 'pages#index'
   get '/contact', to: 'pages#contact', as: :contact
   resources :products do 
     resources :reviews, only: [:edit, :create, :update, :destroy]
   end
   resources :users, only: [:new, :create]
   resources :sessions, only: [:new, :create, :destroy]
   get '/products/:id/reviews', to: redirect('/products/:id/#reviews')

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews
  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    "%.2f" % price_in_dollars
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  PRODUCT_ATTR = [:name, :description, :price_in_cents]
  before_filter -> { load_product(:id) }, only: [:show, :edit, :update, :destroy]    #from application_controller  

  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Product.all
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @ajax = true;   #ajaxified creation
    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(secure_params(:product, PRODUCT_ATTR))
    if @product.save
      redirect_to products_path, notice: "Product created successfully"
    else
      flash.now['alert'] = 'Failure when creating product'
      render :new
    end
  end

  def update
    if @product.update_attributes(secure_params(:product, PRODUCT_ATTR))
      redirect_to product_path, notice: "Product updated successfully"
    else
      flash.now['alert'] = 'Failure when updating product'
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: "Product deleted"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= render 'shared/form_header', :errors => @product.errors %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.text_field :price_in_cents %>
  </div>
  <div class="actions">
    <% if @product.errors.any? %>
      <p class="error">Please, make sure all fields are correct before submitting</p> 
    <% end %>
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<% if false %>
If wrapping tag argument passed, that one used instead of anchor and the product's name is hidden. Based on: http://stackoverflow.com/questions/6196297/render-collection-wrap-each-item
<% end %>
<% @rendered_content = capture do %>
  <dl>
    <%= content_tag(:dt, product.name) unless (defined?(wrap_in) && !wrap_in.blank?) %>
    <dd class="price<%= ' inverted' if (defined?(wrap_in) && !wrap_in.blank?) %>"><%= product.formatted_price %></dd>
    <dd><%= product.description %></dd>
  </dl>
<% end %>

<% if defined?(wrap_in) && !wrap_in.blank? %>
  <%= content_tag(wrap_in, @rendered_content, class: "product") %>
<% else %>
  <%= link_to @rendered_content, product_path(product), class: "product" %> 
<% end %>

app/views/products/_reviews.html.erb
<%-# Only list reviews if they are there! -%>
<%  num_reviews = @product.reviews.count
    if num_reviews > 0 
%>
  <h2><span id="review-counter"><%= num_reviews %></span> Reviews</h2>
  <%= render @product.reviews %>
  <h3 class="review-form-title">New review</h3>
<% else %>
  <h2 class="review-form-title">New review</h2>
  <p>Be the first to review this product!</p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>
<%= render 'form' %>

app/views/products/index.html.erb
<div class="title">
  <h1>Products</h1>
  <%= link_to "Add", new_product_path, title: "Add a new product" %>
</div>
<div class="product-list">
  <% if @products.count > 0 %>
    <%= render @products %>
  <% else %>
    <h2>No products found</h2>
  <% end %>
</div>

app/views/products/index.js.erb
$(".placeholder").html("<%= j(render @products) %>");
$('body').animate({
    scrollTop: $(".placeholder").offset().top
}, 1000);

app/views/products/new.html.erb
<h1>New product</h1>
<%= render 'form' %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<%= render @product, :wrap_in => :div %>
<%= link_to 'Edit', edit_product_path(@product), title: "Change this product's details" %>
<%= link_to 'Delete', product_path(@product), title: "Delete this product", :'data-method' => 'delete' %>  

<% if false %>
Note that paths are absolute to avoid a missing :id error when recovering from an error in review form (from /products/:product_id/reviews).
<% end %>
<div id="review-list">
  <%= render :partial => "products/reviews" %>
</div>

<!-- Show review form only if logged in -->
<% if current_user %>
  <%= render 'reviews/form' %>
<% else %>
  <p>Please <%= login_link %> or <%= signup_link %> to add a review.</p>
<% end %>

<%= javascript_include_tag params[:controller] %>