config/routes.rb
Rails.application.routes.draw do

   root 'pages#index'
   get '/contact', to: 'pages#contact', as: :contact
   resources :products do 
     resources :reviews, only: [:edit, :create, :update, :destroy]
   end
   resources :users, only: [:new, :create]
   resources :sessions, only: [:new, :create, :destroy]
   get '/products/:id/reviews', to: redirect('/products/:id/#reviews')

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  REVIEW_ATTR = [:comment, :product_id]
  before_filter -> { load_product(:product_id) }  #load_product in application_controller
  before_filter :load_review, only: [:edit, :update, :destroy]
  before_filter :ensure_logged_in, only: [:create, :update, :destroy]

  def edit
    @ajax = false;  #ajax disabled; edition would well be implemented in ajax in the real world.
  end

  def create
    @review = @product.reviews.build(secure_params(:review, REVIEW_ATTR))
    @review.user = current_user
    respond_to do |format|
      if @review.save
        format.html { redirect_to current_product, notice: 'Review created successfully' }
        format.js {} #fetches app/views/reviews/create.js.erb
      else
        format.html { render 'products/show', alert: 'Failure when creating review' }
        format.js {} #fetches app/views/reviews/create.js.erb
      end
    end
  end

  def update 
    if @review.update_attributes(secure_params(:review, REVIEW_ATTR))
      redirect_to current_product, notice: 'Review updated successfully'
    else
      flash.now['alert'] = 'Failure when updating review'
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to current_product, notice: "Review deleted"
  end

  private
  def load_review
    @review = Review.find(params[:id])
  end

  def current_product
    product_path(@review.product_id)  #chose to grab id from active record in case route no longer nested
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%-# This way, active record can infer the value for the FK in Reviews -%> 
<%= form_for [@product, @review], :remote => @ajax do |f| %>    
  <div id="review-form-errors">   
    <%= render 'shared/form_header', :errors => @review.errors %>
  </div>
  <div class="field">
    <%= f.label :comment %><br/>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<p><%= review.comment %></p>
<% if review.user != nil %>
  <p>
    By <em><%= review.user.username %></em> on <%= formatted_datetime(review.created_at) %>
  </p>
<% end %>
<% if current_user && review.id %>
  <%= link_to 'Edit', edit_product_review_path(@product, review), title: "Change this review" %>
  <%= link_to 'Delete', product_review_path(@product, review), title: "Delete this review", :'data-method' => 'delete' %>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render 'shared/form_header', :errors => @review.errors) %>");
<% else %>
  $("#review-form-errors").html("");      //clear any previous errors
  $reviewCounter = $("#review-counter");  //number in heading of review list
  if ($reviewCounter.length) {            //if there's a counter, at least 1 review has already been added
      $reviewCounter.text(parseInt($reviewCounter.text(), 10) + 1);                  //increases review counter 
      $(".review-form-title").before("<%= escape_javascript(render @review) %>");    //h2 -> h3 for title of review form if at least 1 review exists  
  } else {
      $("#review-list").html("<%= escape_javascript(render :partial => 'products/reviews') %>");
  }
  $(".recent").removeClass("recent");                 //removes any previous highlighting
  $("#review-list p").slice(-2).addClass("recent");   //highlights newly added review (a review is basically 2 <p>)
  $("#new_review textarea").val("");                  //clear text area
<% end %>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Edit review</h1>
<% if current_user %>
  <%= render 'form' %>
<% else %>
  <p>Please <%= login_link %> to edit this review.</p>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>